Repository analogwp/analogwp-templates, pull requests merged in 2020-02, with the labels that each got.

#317 Update SK Pro settings tab
  assets/css/admin-settings.css
  inc/settings/views/html-admin-settings-gopro.php
Labels: cleanup

#304 Update Elementor Kit option with Respect to GSK settings
  inc/settings-helpers.php
  inc/settings/class-settings-general.php
Labels: ON_HOLD, P0, dependencies

#306 Add Elementor Required Version
  analogwp-templates.php
Labels: ON_HOLD, P0, dependencies

#299 Issue/281 - Feature/281 kit migration
  .travis.yml
  analogwp-templates.php
  assets/css/admin-settings.css
  assets/css/elementor-modal.css
  composer.json
  inc/Core/Util/Migration.php
  inc/Utils.php
  inc/admin/Notice.php
  inc/api/class-local.php
  inc/api/class-remote.php
  inc/class-elementor.php
  inc/cli/commands.php
  inc/elementor/class-ang-action.php
  inc/elementor/class-colors.php
  inc/elementor/class-tools.php
  inc/elementor/class-typography.php
  inc/elementor/js/ang-action.js
  inc/elementor/kit/Kits_List_Table.php
  inc/elementor/kit/Manager.php
  inc/elementor/kit/kit-content.json
  inc/elementor/sections/background-color-classes.php
  inc/register-settings.php
  inc/settings-helpers.php
  inc/settings/class-settings-general.php
  inc/settings/views/html-admin-settings-gopro.php
  inc/upgrade-functions.php
  package.json
  readme.txt
  src/js/app/App.js
  src/js/app/Templates.js
  src/js/app/api.js
  src/js/app/popup.js
  src/js/app/popups/ImportTemplate.js
  src/js/app/stylekits/stylekits.js
Labels: ON_HOLD

#324 Fix Quick Edit & Bulk Edit actions for Style Kit assignment
  inc/Utils.php
  inc/class-quick-edit.php
Labels: P0, Type: Bug

#331 Manage SK Panels Subtab changes
  inc/class-admin-settings.php
  inc/settings/class-settings-general.php
Labels: Type: Enhancement, cleanup, 👉🏻 For Pro

#338 Fix Icon Box stacked view icon color
  inc/elementor/class-colors.php
Labels: Type: Bug, cleanup

#341 Update Kit Save As popup notification
  inc/api/class-local.php
  inc/elementor/js/ang-action.js
Labels: KITS

#349 Revise Edit Style Kit
  inc/elementor/class-typography.php
Labels: KITS

#347 Revise Tools panel to Theme Style Kit
  inc/elementor/class-typography.php
Labels: KITS

#350 Revise Style Kits Menu
  inc/register-settings.php
  src/js/app/App.js
Labels: KITS

#336 Onboarding Screen After Migration
  assets/css/onboarding-screen.css
  inc/register-settings.php
Labels: P1, Type: Feature

#359 Improve initialization
  analogwp-templates.php
  inc/Plugin.php
Labels: P0, Type: Enhancement
